### ISSUE TITLE
Create a menu control

### ISSUE THREAD

**Issue by capnmidnight** [capnmidnight/Primrose#103]
Something that makes selecting from a series of choices and drilling down into multiple levels easy for the user to set up.

**Comment by micahbales** [comment]
I may be missing something obvious here, but I'm not sure which menu this would be. Can you give guidance about the best way to start working on this issue? Perhaps describe what choices & levels we'll be selecting. Also, what view is this menu in?

Thanks!

**Comment by capnmidnight** [comment]
In the browser, we have two different graphics systems, the declarative Document Object Model, where we can write HTML or SVG code that describes the desired end result of our image and have the browser figure out the drawing calls to produce that image, or procedural WebGL, where we have to instruct the system directly on how to paint the objects we care to see.

Making a menu system in DOM is pretty easy. [There are standard HTML elements for menus](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu). In the vast majority of cases where they aren't implemented, [we frequently make menus out of unordered lists](https://www.w3schools.com/css/css_navbar.asp). [Here's one built in React with a particularly concise example](https://github.com/react-component/menu). [Here's one in Ember](https://github.com/null-null-null/ember-flex-menu).

Unfortunately, the DOM and WebGL don't compose together very well. You can make DOM appear on top of WebGL, and if you work at it a little bit you can make WebGL appear on top of DOM, but you can't interleave them in a way that makes sense in the 3D construct of the scene. Hence why [Primrose has a from-scratch text editor control](https://www.primrosevr.com/doc/#Primrose_Text) in it already. 

Also, I hope to one day make Primrose work in systems other than the browser, which almost universally have a JavaScript interpreter with some form of WebGL capability, but not any sort of DOM. Some examples of these systems are [AltspaceVR](https://altvr.com/) and [High-Fidelity](https://highfidelity.com/).

So, this issue is about making an API for describing menus, rather than creating any particular menu. We need a way to be able to define menus semantically, ala HTML (and cribbing the HTML spec for the structure of such a thing is perfectly acceptable). The API would take that description and add objects to the 3D scene. Which particular objects and where it adds them would in part be influenced by the user's capabilities. Declarative description languages are typically a little better for implementing accessibility features than procedural ones.

Indeed, cribbing the HTML spec for the structure would be a good idea for the future goal of using HTML as a scene description language. A-Frame does this to some extent, but I think they go too far with [creating custom elements for no particularly good reason](https://aframe.io/docs/0.5.0/primitives/a-image.html). If Primrose had an HTML-based scene definition that was 1-to-1 with HTML, then we could conceivably take arbitrary HTML documents and re-interpret them for VR. 

Long story short: HTML is declarative, WebGL is procedural. We like the declarativeness of HTML, but long-term we can only count of having the proceduralness of WebGL. So we reimplement HTML (which is not as hard as it sounds, and as long as we're only in the browser, can be cheated for the time being).

We already have [clickable objects](https://www.primrosevr.com/demos/shadows.html). We have the ability to [create 3D text](https://github.com/NotionTheory/Primrose/blob/19ff15f844e7061d4138cddbde84d148fceeece3/src/Primrose/BrowserEnvironment.js#L521-L554). We can also [create basic, 2D text](https://www.primrosevr.com/doc/#Primrose_Controls_PlainText). These can be combined with [boxes](https://www.primrosevr.com/doc/#LiveAPI_box) to give a sense of [blocks of text and borders](https://www.primrosevr.com/demos/calendar.html). What we need is a system that can describe the structure of the menu, with event handlers, and combine the previous graphics primitives to make a system that reacts to the user.

It'd be okay if this menu at first only generated stacks of boxes in a simple, linear relationship, or required the developer to specify the direction in which to flow the boxes, but eventually the layout of the menu would reflow automatically, depending on the user's system, in similar sense to have we have [sites that can reflow their content progressively from desktop systems to smartphones](https://sitesforprofit.com/incredibly-useful-list-of-responsive-navigation-and-menu-patterns).
