### ISSUE TITLE
Write a wiki page on "VR-ready PCs"

### ISSUE THREAD

**Issue by capnmidnight** [capnmidnight/Primrose#144]
For anyone just getting started in VR, it can be confusing as to what is necessary to get up and running with development work. Let's [make a document in the Wiki](https://github.com/NotionTheory/Primrose/wiki/VR-ready-PC) to cover some of the issues.

Include details on:

- [ ] building a PC for the HTC Vive
- [ ] building a PC for the Oculus Rift
- [ ] getting a Samsung Gear VR
- [ ] getting a Google Pixel with Daydream
- [ ] constructing your own Google Cardboard setup

**Comment by upodroid** [comment]
I'll write this up.

**Comment by capnmidnight** [comment]
Cool beans, thanks

**Comment by capnmidnight** [comment]
Instead of being a short list of one specific hardware profile, I'd like this document to be more of a discussion on each of the different parts, why you need them, and what alternatives are available.

For example, you've written that one needs a "Seagate Barracuda 1TB HDD". There's no requirement for any particular hard drive, though people might want to have at least 500GB or so, given how large Windows 10 and many of the software packages you'll end up using during development have gotten.

Additionally, there's no mention of mobile VR, what you need to get started developing for the Gear VR or Daydream or just Google Cardboard. These requirements will be much, much lower and I think for a lot of people it would be helpful to have a document explain that this path is available.

Thanks for getting started on this. Please let me know if you'd like to continue on the document.

**Comment by upodroid** [comment]
Hello
I will get it done as soon as possible. Been busy with studies :D
