### ISSUE TITLE
Support Gear VR controller through WebBluetooth in Google Cardboard

### ISSUE THREAD

**Issue by capnmidnight** [capnmidnight/Primrose#156]
The Gear VR controller is a standard Bluetooth LE device. The experimental WebBluetooth API on Google Chrome on Android allows for accessing BLE devices directly.

**Comment by sykosoft** [comment]
It appears that you could use this work already done:

https://jsyang.ca/gearvr-controller-webbluetooth/index.html

https://github.com/jsyang/gearvr-controller-webbluetooth

I became interested in this because best buy was clearancing out the controllers and found this work already done
