### ISSUE TITLE
Uncompatible with Vimium extension

### ISSUE THREAD

**Issue by tianshuo** [capnmidnight/Primrose#16]
Usually textboxes don't interfere with the vimium extension, but because there is no input box to capture keystrokes, the vimium captures keystrokes before inputting. 
Solutions could be:
1. An hidden but focused textbox to capture keystrokes
2. Prevent default when "focused" on canvas

**Comment by capnmidnight** [comment]
Thanks for the report. I'm a bit surprised that is the case, because it does actually preventDefault, pretty much always. I know that isn't ideal, but I was slapping things together today.

**Comment by capnmidnight** [comment]
I've only done a cursory test, but this should be fixed now. There is now a hidden textbox that triggers the key events, and the key events are only "preventDefault"ed when they are specifically within the Primrose context. You wouldn't mind testing it out again, would you? If you deem this fixed, please close the issue. http://capnmidnight.github.io/Primrose/

**Comment by tianshuo** [comment]
@capnmidnight Works marvelously! Great!

**Comment by capnmidnight** [comment]
Thanks!
