### ISSUE TITLE
(Semi)transparent background in theme overrides at each render

### ISSUE THREAD

**Issue by dkaraush** [capnmidnight/Primrose#163]
I thought that it'll be great to make semitransparent editor, but it seems there is no support for now: I suppose that is lack of `clearRect` and using `fillRect` firstly.

How to reproduce: set theme of Primrose instance to have `.regular.backColor` be `rgba(255, 255, 255, 0.5)`.

I see two ways to solve it: simply put `clearRect` or add event `preupdate` (or `prerender`), that will be fired before render happens, so I can make `clearRect` on my own.

Let me know if I need to provide more detailed example.

**Comment by capnmidnight** [comment]
I see, the background needs to always be cleared, even when it's filled, because using a semi-transparent fill color will eventually saturate to completely opaque.

I see no problem with always calling clearRect first, and then only conditionally calling fillRect.

**Comment by dkaraush** [comment]
Hello, so glad you fixed this so fast, 3 hours, I didn't expect this :)
Closing issue

**Comment by capnmidnight** [comment]
Well, when you don't have any external dependencies in a project, it's pretty easy to pick up where you left off :)
