### ISSUE TITLE
Execute code command pops up OSX Yosemite "Searching this Mac"

### ISSUE THREAD

**Issue by mchogan** [capnmidnight/Primrose#27]
**option + command + space** is the native OSX command to launch Finder's "Searching this Mac" window. That prevents Primrose from executing the editor code on Mac OSX.

Recommend switching to **option + command + e** for 'execute'.

**Comment by capnmidnight** [comment]
Thanks for the report. That is a pretty simple fix.

**Comment by capnmidnight** [comment]
This is fixed now.
