### ISSUE TITLE
keystroke to summon editor

### ISSUE THREAD

**Issue by blazespinnaker** [capnmidnight/Primrose#73]
It'd be cool to move the editor to wherever I'm standing.   Hopefully I'll have bandwidth to do a pull request

**Comment by capnmidnight** [comment]
Eventually, I want to have an editor that is always with you, while also having editors attached to any object you create. You would basically have an editor for every node of your scene graph, and use them to edit specific details on the fly.

**Comment by capnmidnight** [comment]
New trello card https://trello.com/c/IiVWxF37

**Comment by capnmidnight** [comment]
The editor now sits on a 3D layer called the "UI" layer. It follows you around as you move. I gave it some lag to the movement so you can move around and not have the text editor strictly locked to you. 

You can also do CTRL+SHIFT+E to show/hide the editor. So between these two things, you should always be able to get to the editor no matter where you are in the scene.
